### ISSUE TITLE
CanIUse unit test fails in IE11

### ISSUE THREAD

**Issue by jacobrossi** [Modernizr/Modernizr#1511]
In IE11, browse to http://modernizr.github.io/Modernizr/test/

Expect: all tests pass
Actual: Test bucket # 20 fails (CanIUse)

    Died on test #1    at window.caniusecb (http://modernizr.github.io/Modernizr/test/js/unit-caniuse.js:174:3)
       at Global code (http://caniuse.com/jsonp.php?callback=caniusecb:1:1): Unable to get property 'undefined.undefined' of undefined or null referenceSource:  TypeError: Unable to get property 'undefined.undefined' of undefined or null reference
       at Anonymous function (http://modernizr.github.io/Modernizr/test/js/unit-caniuse.js:198:7)

I'm opening the issue here to track the impact on Modernizr. But it looks like an issue in uaparser.js  https://github.com/tobie/ua-parser/

Once I confirm that, I'll post an issue there and link back here.

**Comment by patrickkettner** [comment]
we actually have a had ported version of uaparser done by @paulirish. It was made before they added it upstream, so it was missing. I patched it locally, and will be pushing up the fixes with a few others for IE 11 soon.

**Comment by patrickkettner** [comment]
fixed with bed5f7c699c5a774cebdd1937a142eb30896a796
