### ISSUE TITLE
Modernizr (requirejs?) windows bug

### ISSUE THREAD

**Issue by dmzkrsk** [Modernizr/Modernizr#1523]
I use modernizr 3.0.0-alpha in my gulp task (via `gulp-modernizr`) and it fails with error

```
Error: Tried loading "src/generate.js" at src/generate.js then tried node's require("src/generate.js") and it failed with error: Error: Cannot find module 'src/generate.js'
    at R:\Dev\django-stage\md-bug\node_modules\gulp-modernizr\node_modules\customizr\node_modules\modernizr\node_modules\requirejs\bin\r.js:2552:27
    at Object.context.execCb (R:\Dev\django-stage\md-bug\node_modules\gulp-modernizr\node_modules\customizr\node_modules\modernizr\node_modules\requirejs\bin\r.js:1916:33)
    at Object.Module.check (R:\Dev\django-stage\md-bug\node_modules\gulp-modernizr\node_modules\customizr\node_modules\modernizr\node_modules\requirejs\bin\r.js:1125:51)
    at Object.Module.enable (R:\Dev\django-stage\md-bug\node_modules\gulp-modernizr\node_modules\customizr\node_modules\modernizr\node_modules\requirejs\bin\r.js:1409:22)
    at Object.context.enable (R:\Dev\django-stage\md-bug\node_modules\gulp-modernizr\node_modules\customizr\node_modules\modernizr\node_modules\requirejs\bin\r.js:1777:39)
    at Function.req.get (R:\Dev\django-stage\md-bug\node_modules\gulp-modernizr\node_modules\customizr\node_modules\modernizr\node_modules\requirejs\bin\r.js:2476:33)
    at Object.localRequire [as require] (R:\Dev\django-stage\md-bug\node_modules\gulp-modernizr\node_modules\customizr\node_modules\modernizr\node_modules\requirejs\bin\r.js:1650:40)
    at requirejs (R:\Dev\django-stage\md-bug\node_modules\gulp-modernizr\node_modules\customizr\node_modules\modernizr\node_modules\requirejs\bin\r.js:2003:24)
    at Object.<anonymous> (R:\Dev\django-stage\md-bug\node_modules\gulp-modernizr\node_modules\customizr\node_modules\modernizr\lib\build.js:123:18)
    at Module._compile (module.js:456:26)
```

This line causes an error:

```
var generate = requirejs(__dirname + '/../src/generate.js');
```

I checked, that the path exists.

The line before

```
var generateBanner = requirejs(__dirname + '/generate-banner.js');
```

has no problem

I reproduced this bug on clean install with 

```
npm install --save-dev gulp gulp-modernizr
```

and `gulpfile.js`:

```
var gulp       = require('gulp');
var modernizr  = require('gulp-modernizr');

gulp.task('default', function() {
    return gulp.src('*.js')
        .pipe(modernizr())
});
```

```
> grunt
```

**Comment by dmzkrsk** [comment]
I use Win8.1 x64 node==0.10.28

**Comment by patrickkettner** [comment]
I will check it out as soon as I can get a windows machine, in the mean time could you try changing it to 

```
var generate = requirejs('generate.js');
```

**Comment by dmzkrsk** [comment]
Didn't help. I also tracked down the issue in requirejs code, posted on their issue tracker jrburke/r.js#779

**Comment by dmzkrsk** [comment]
A hackish solution that worked
```
var generate = requirejs(__dirname.replace(/\\/g, '/') + '/../src/generate.js');
```

**Comment by patrickkettner** [comment]
sorry, I meant to try 
```
var generate = requirejs('generate');
```

`src` is the default path, and it should already be registered. I believe adding the `.js` extension makes it look for it in file mode, rather than by name

**Comment by dmzkrsk** [comment]
Yep, that worked

**Comment by patrickkettner** [comment]
strangly, I just tried running on a windows 7 machine, and it worked without any modifications.

**Comment by patrickkettner** [comment]
great, I will make that change momentarily

**Comment by jon64digital** [comment]
I am still getting this problem with gulp-modernizr. Is that because the gulp plugin isn't using the latest version with the fix committed above?

**Comment by patrickkettner** [comment]
yep. someone else randomly registered the package, before it was supposed to be public. its prerelease software, and so we are not version bumping on commits like we would otherwise. you will need to manually override it with master if you need to use it
