### ISSUE TITLE
module 'file' is broken in Windows, please use node built-in module: 'path'.

### ISSUE THREAD

**Issue by hh9527** [Modernizr/Modernizr#1640]
```
Error: ENOENT, no such file or directory 'c:\home\dws\projects\prel\d:\dws\projects\prel\node_modules\modernizr\feature-detects'
    at Error (native)
    at Object.fs.statSync (fs.js:797:18)
    at Object.exports.walkSync (d:\dws\projects\prel\node_modules\modernizr\node_modules\file\lib\file.js:153:17)
    at Object.<anonymous> (d:\dws\projects\prel\node_modules\modernizr\lib\generate-meta.js:9:6)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

in lib/generate-meta.js
`var viewRoot = file.path.abspath(__dirname + '/../feature-detects');`

got the wrong result:
```
c:\home\dws\projects\prel\d:\dws\projects\prel\node_modules\modernizr\feature-detects
```

**Comment by hh9527** [comment]
oh, it is a dependency problem in my computer. after re install all deps, it is ok.
