### ISSUE TITLE
Installing custom build via bower fails

### ISSUE THREAD

**Issue by thasmo** [Modernizr/Modernizr#1723]
Running `bower install https://modernizr.com/download?dontmin-setClasses-cssclassprefix:has-.zip` fails with:
```shell
bower modernizr#*           not-cached https://modernizr.com/download?dontmin-setClasses-cssclassprefix:has-.zip#*
bower modernizr#*              resolve https://modernizr.com/download?dontmin-setClasses-cssclassprefix:has-.zip#*
bower download#*            not-cached https://modernizr.com/download?dontmin-setClasses-cssclassprefix:has-.zip#*
bower download#*               resolve https://modernizr.com/download?dontmin-setClasses-cssclassprefix:has-.zip#*
bower download#*              download https://modernizr.com/download?dontmin-setClasses-cssclassprefix:has-.zip
bower modernizr#*             download https://modernizr.com/download?dontmin-setClasses-cssclassprefix:has-.zip
bower download#*                 EHTTP Status code of 500

```

**Comment by patrickkettner** [comment]
![image](https://cloud.githubusercontent.com/assets/465414/10589818/fde45af2-7672-11e5-895f-3467339f4f0b.png)

Not for me :/

Can you `bower cache clean` and let me know what version you are working with?

**Comment by thasmo** [comment]
Ye, I did that already to be sure it's not the cache. :l

**Comment by patrickkettner** [comment]
what version of bower are you using

On Mon, Oct 19, 2015 at 3:07 PM, Thomas Deinhamer <notifications@github.com>
wrote:

> Ye, I did that already to be sure it's not the cache. :l
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Modernizr/Modernizr/issues/1723#issuecomment-149331601>
> .
>



-- 
patrick

**Comment by thasmo** [comment]
Your's was cached btw. - and what's that e-tag hash at the end of the URL?

**Comment by thasmo** [comment]
Bower version 1.6.3

**Comment by patrickkettner** [comment]
![image](https://cloud.githubusercontent.com/assets/465414/10589884/6bc306a4-7673-11e5-8ab6-a8efd9e2e25f.png)

sorry, clean cache works still

**Comment by patrickkettner** [comment]
i'll pin mine locally to that and try again

**Comment by thasmo** [comment]
Running `bower install --verbose ...` gives me this; does this help?
```shell

Stack trace:
Error: Status code of 500
    at createError (C:\Users\thasmo\AppData\Roaming\npm\node_modules\bower\lib\util\createError.js:4:15)
    at Request.<anonymous> (C:\Users\thasmo\AppData\Roaming\npm\node_modules\bower\lib\util\download.js:79:36)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at Request.onRequestResponse (C:\Users\thasmo\AppData\Roaming\npm\node_modules\bower\node_modules\request\request.js:1176:10)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:415:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at TLSSocket.socketOnData (_http_client.js:305:20)
From previous event:
    at RetryOperation._fn (C:\Users\thasmo\AppData\Roaming\npm\node_modules\bower\lib\util\download.js:35:12)
    at RetryOperation.attempt (C:\Users\thasmo\AppData\Roaming\npm\node_modules\bower\node_modules\retry\lib\retry_operation.js:56:8)
    at download (C:\Users\thasmo\AppData\Roaming\npm\node_modules\bower\lib\util\download.js:32:15)
    at UrlResolver._download (C:\Users\thasmo\AppData\Roaming\npm\node_modules\bower\lib\core\resolvers\UrlResolver.js:123:12)
    at UrlResolver._resolve (C:\Users\thasmo\AppData\Roaming\npm\node_modules\bower\lib\core\resolvers\UrlResolver.js:96:17)

Console trace:
Error
    at StandardRenderer.error (C:\Users\thasmo\AppData\Roaming\npm\node_modules\bower\lib\renderers\StandardRenderer.js:82:37)
    at Logger.<anonymous> (C:\Users\thasmo\AppData\Roaming\npm\node_modules\bower\bin\bower:110:22)
    at emitOne (events.js:77:13)
    at Logger.emit (events.js:169:7)
    at Logger.emit (C:\Users\thasmo\AppData\Roaming\npm\node_modules\bower\node_modules\bower-logger\lib\Logger.js:29:39)
    at C:\Users\thasmo\AppData\Roaming\npm\node_modules\bower\lib\commands\index.js:48:20
    at _rejected (C:\Users\thasmo\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:844:24)
    at C:\Users\thasmo\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:870:30
    at Promise.when (C:\Users\thasmo\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (C:\Users\thasmo\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:788:41)
System info:
Bower version: 1.6.3
Node version: 4.2.1
OS: Windows_NT 10.0.10240 x64
```

**Comment by patrickkettner** [comment]
Thanks! But the error is server side, so there isn't much bower can tell
us. Im diggin in the pm2 logs to try and find your err.

**Comment by thasmo** [comment]
@patrickkettner, I got the exact same error running on a remote Linux machine, using bower 1.6.3 on node 0.12.7.

**Comment by patrickkettner** [comment]
as of bower/bower@0bb1536, bower is no longer sending a user-agent when it sends the request (which is what is triggering the 500). Im digging into that commit further to try and figure out whats going on

**Comment by thasmo** [comment]
Awesome, thanks!

**Comment by thasmo** [comment]
@patrickkettner, any success?

**Comment by patrickkettner** [comment]
@thasmo it was merged into bower. Update the the latest version and you should be good to go!

**Comment by thasmo** [comment]
@patrickkettner, awesome! Works - except for #1735. ;)
