### ISSUE TITLE
No longer possible to pass path to custom tests to Modernizr.build

### ISSUE THREAD

**Issue by terinjokes** [Modernizr/Modernizr#1799]
It's no longer possible to pass the paths to custom tests to Modernizr.build, as it fails trying to load the property while generating the buildQuery. This used to work with previous versions of Modernizr v3.

**Comment by patrickkettner** [comment]
Could you give more details on what you are doing and he specific errors you are receiving?

**Comment by terinjokes** [comment]
```javascript
var modernizr = require('modernizr');

modernizr.build({
  'feature-detects': [
    'test/storage/localstorage',
    require.resolve('./lib/modernizr/saveblob')
  ]
}, function(result) {
  console.log(result);
});
```

```
/Users/terin/Development/development/node_modules/modernizr/lib/build-query.js:22
        property.replace('-', '_');
                ^

TypeError: Cannot read property 'replace' of undefined
    at /Users/terin/Development/development/node_modules/modernizr/lib/build-query.js:22:17
    at arrayMap (/Users/terin/Development/development/node_modules/lodash/index.js:1406:25)
    at Function.map (/Users/terin/Development/development/node_modules/lodash/index.js:6710:14)
    at generateBuildQuery (/Users/terin/Development/development/node_modules/modernizr/lib/build-query.js:17:19)
    at banners (/Users/terin/Development/development/node_modules/modernizr/lib/generate-banner.js:16:17)
    at build (/Users/terin/Development/development/node_modules/modernizr/lib/build.js:81:16)
    at Object.build (/Users/terin/Development/development/node_modules/modernizr/lib/build.js:156:50)
    at Object.<anonymous> (/Users/terin/Development/development/index.js:3:11)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
```

**Comment by patrickkettner** [comment]
Thanks so much, will be fixed soon

**Comment by terinjokes** [comment]
@patrickkettner Do you have an idea on what the timeline for "soon" might be? It's currently a blocker for us. I can easily send a PR to fix the issue, but I don't know what the expected behavior should be: having custom tests means a build query does not accurately represent the build, so should it be skipped?

**Comment by patrickkettner** [comment]
I just woke up, so like..less than 8 hours ? Depends on if I can push my
changes on the plane or ot.

On Wed, Dec 9, 2015 at 10:07 AM, Terin Stock <notifications@github.com>
wrote:

> @patrickkettner <https://github.com/patrickkettner> Do you have an idea
> on what the timeline for "soon" might be? It's currently a blocker for us.
> I can easily send a PR to fix the issue, but I don't know what the expected
> behavior should be: having custom tests means a build query does not
> accurately represent the build, so should it be skipped?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Modernizr/Modernizr/issues/1799#issuecomment-163343082>
> .
>



-- 
patrick

**Comment by terinjokes** [comment]
@patrickkettner No worries. I didn't know if "soon" meant hours, days, or weeks. :)

**Comment by terinjokes** [comment]
@patrickkettner buildQuery now doesn't error, but it's still not possible to include a custom test. The logic located at [src/generate.js](https://github.com/Modernizr/Modernizr/blob/0b3cd01198ed25622ba57efa90e2ef1635866df9/src/generate.js#L44-L48) does not allow absolute paths as "test/" is prepended to the path.

A trick with an older version of Modernizr v3 was to generate a relative path back to the custom tests, but this also doesn't work since RequireJS attempts to load "node_modules/modernizr/lib/../src/test/../../../../../custom/test/path.js" (the root directory + test being prepended + the relative path) and the "modernizr/src/test" folder doesn't exist.

**Comment by patrickkettner** [comment]
Ugh. Sorry. 

will fix asap

**Comment by terinjokes** [comment]
:laughing: :+1:

**Comment by henhan** [comment]
Any update on fixing this issue? It's a bit annoying since the whole customTests option is broken.

**Comment by benmcginnis** [comment]
@terinjokes is this ever going to merge?

**Comment by patrickkettner** [comment]
We are rewriting the infrastructure to be es6 modules, so the issue will be fixed in the near future, but it is unlikely that this specific code change will be merged.

**Comment by ctjhoa** [comment]
@patrickkettner still no news?
