### ISSUE TITLE
npm@3.5.2 install fail

### ISSUE THREAD

**Issue by nuxdie** [Modernizr/Modernizr#1806]
`npm-debug.log` [full log](https://gist.githubusercontent.com/nuxdie/427383f0140dfc0e5125/raw/81a192163446466caf4f2d6942303d56b18ecec6/npm-debug.log)

````
15440 verbose stack TypeError: Cannot read property 'target' of null
15440 verbose stack     at module.exports (/usr/local/lib/node_modules/npm/lib/install/filter-invalid-actions.js:24:35)
15440 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
15440 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
15440 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
15440 verbose stack     at Object.Installer.computeLinked (/usr/local/lib/node_modules/npm/lib/install.js:411:41)
15440 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
15440 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
15440 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
15440 verbose stack     at module.exports (/usr/local/lib/node_modules/npm/lib/install/diff-trees.js:50:3)
15440 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
15441 verbose cwd /Users/a.tsatsin/pro/lj/node_modules/modernizr
15442 error Darwin 15.2.0
15443 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
15444 error node v5.2.0
15445 error npm  v3.5.2
15446 error Cannot read property 'target' of null
15447 error If you need help, you may report this error at:
15447 error     <https://github.com/npm/npm/issues>
15448 verbose exit [ 1, true ]
````

**Comment by patrickkettner** [comment]
what is it you tried to install?

**Comment by nuxdie** [comment]
````
npm i modernizr
cd node_modules/modernizr
npm i
````

**Comment by patrickkettner** [comment]
why are you running install inside of an installed module?

**Comment by nuxdie** [comment]
to build 
`./bin/modernizr -c lib/config-all.json`

**Comment by patrickkettner** [comment]
that is not a requirement.

```
npm i modernizr
./node_modules/.bin/modernizr -c ./config.json
```

**Comment by nuxdie** [comment]
10q that helps.
but why install fails in the first place?

**Comment by patrickkettner** [comment]
I have no idea. There is never a reason to do what you are doing (that I can think of), so it is more than likely a bug with npm.

cheers!
