### ISSUE TITLE
Installing via build url fails

### ISSUE THREAD

**Issue by jamie-robertson** [Modernizr/Modernizr#1870]
When running bower install --save http://modernizr.com/download/?-bgsizecover-cssanimations-csscalc-cssgradients-flexbox-flexboxlegacy-lastchild-svg-mq-printshiv-setclasses-testprop.zip

it fails to install the custom build, but if i use any urls found on other tickets they work fine.  do builds take time to be generated for download?

**Comment by patrickkettner** [comment]
No, they don't. What DOES happen?

**Comment by jamie-robertson** [comment]
the console tells me this

`bower                       not-cached http://modernizr.com/download/?-bgsizecover-cssanimations-csscalc-cssgradients-flexbox-flexboxlegacy-lastchild-svg-mq-printshiv-setclasses-testprop.zip#*
bower                          resolve http://modernizr.com/download/?-bgsizecover-cssanimations-csscalc-cssgradients-flexbox-flexboxlegacy-lastchild-svg-mq-printshiv-setclasses-testprop.zip#*
bower                            error Arguments to path.join must be strings

Stack trace:
TypeError: Arguments to path.join must be strings
    at Object.posix.join (path.js:488:13)
    at UrlResolver._download (/usr/local/lib/node_modules/bower/lib/core/resolvers/UrlResolver.js:109:21)
    at UrlResolver._resolve (/usr/local/lib/node_modules/bower/lib/core/resolvers/UrlResolver.js:96:17)
From previous event:
    at UrlResolver.Resolver.resolve (/usr/local/lib/node_modules/bower/lib/core/resolvers/Resolver.js:100:6)
    at PackageRepository._resolve (/usr/local/lib/node_modules/bower/lib/core/PackageRepository.js:175:21)
    at /usr/local/lib/node_modules/bower/lib/core/PackageRepository.js:77:29

Console trace:
Trace
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:17)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:110:22)
    at Logger.emit (events.js:107:17)
    at Logger.emit (/usr/local/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/index.js:40:20
    at _rejected (/usr/local/lib/node_modules/bower/node_modules/q/q.js:797:24)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:823:30
    at Promise.when (/usr/local/lib/node_modules/bower/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/node_modules/q/q.js:741:41)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:557:44`

**Comment by patrickkettner** [comment]
I reverted back to 1.3.12 to replicate, and did. You can remove the `/` between `download` and `?` to avoid the issue . If you update to the latest bower versions you won't have to do anything - it just works.

good luck!

**Comment by jamie-robertson** [comment]
nice one, thanks!
