### ISSUE TITLE
Tests fail under node10

### ISSUE THREAD

**Issue by rejas** [Modernizr/Modernizr#2332]
`npm run test` fails when run under node 10:

```
~/projects/Modernizr$ npm run test

> modernizr@3.6.0 test /home/rejas/projects/Modernizr
> grunt test --stack

(node:105) ExperimentalWarning: The http2 module is an experimental API.
Running "clean:dist" (clean) task
>> 0 paths cleaned.

Running "eslint:target" (eslint) task

Running "pug:compile" (pug) task
>> 3 files created.

Running "instrument:files" (instrument) task
Instrumented 53 files

Running "env:coverage" (env) task

Running "mochaTest:test" (mochaTest) task


  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․

  320 passing (3s)


Running "generate:dest" (generate) task

Running "connect:server" (connect) task
Started connect web server on http://localhost:9999

Running "mocha:test" (mocha) task
Testing: http://localhost:9999/test/unit.html


  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․

  169 passing (3s)

Fatal error: Callback must be a function
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:167:11)
    at Object.fs.unlink (fs.js:1036:14)
    at File.unlink (/home/rejas/projects/Modernizr/node_modules/temporary/lib/file.js:100:13)
    at cleanup (/home/rejas/projects/Modernizr/node_modules/grunt-lib-phantomjs/lib/phantomjs.js:56:16)
    at Timeout.loopy (/home/rejas/projects/Modernizr/node_modules/grunt-lib-phantomjs/lib/phantomjs.js:123:9)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! modernizr@3.6.0 test: `grunt test --stack`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the modernizr@3.6.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rejas/.npm/_logs/2018-06-15T15_08_57_744Z-debug.log
```

**Comment by niksy** [comment]
@rejas Maybe we should first try to run it on Node 8 since it’s currently recommended for most users, and then work up to Node 10 support?

It works on Node 8, except there is an issue #2355.

**Comment by rejas** [comment]
@niksy I dont care where we start getting updated node versions to run :-)
