### ISSUE TITLE
Console node ./bin/modernizr -c ./lib/config-all.json throws out error

### ISSUE THREAD

**Issue by devprojectsapps** [Modernizr/Modernizr#2509]
Hi.
I am using version 3.9.0.
I want to create the modernizr.js.
I open a new console and enter this:
node ./bin/modernizr -c ./lib/config-all.json

I am getting this error:
module.js:549
    throw err;
    ^

Error: Cannot find module 'file'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/..../app/bower_components/modernizr/lib/metadata.js:2:12)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by rejas** [comment]
Could you try v3.9.1 which fixed an issued die people running node <= 8 ?Am 08.03.20, 20:36 schrieb devprojectsapps <notifications@github.com>:

  Hi. I am using version 3.9.0. I want to create the modernizr.js. I open a new console and enter this: node ./bin/modernizr -c ./lib/config-all.json 
  I am getting this error: module.js:549 throw err; ^ 
  Error: Cannot find module 'file' at Function.Module._resolveFilename (module.js:547:15) at Function.Module._load (module.js:474:25) at Module.require (module.js:596:17) at require (internal/module.js:11:18) at Object. (/..../app/bower_components/modernizr/lib/metadata.js:2:12) at Module._compile (module.js:652:30) at Object.Module._extensions..js (module.js:663:10) at Module.load (module.js:565:32) at tryModuleLoad (module.js:505:12) at Function.Module._load (module.js:497:3)

**Comment by devprojectsapps** [comment]
Also i tried this version and get this error :-(

**Comment by rejas** [comment]
what node / npm version are you using ?

**Comment by devprojectsapps** [comment]
node -v results v8.10.0

**Comment by rejas** [comment]
Can't reproduce that with v8.10.0 n my macos. What OS are you using? Have you tried deleting the node_modules dir and the package-lock file and reinstalling your dependencies

**Comment by devprojectsapps** [comment]
I am using Ubuntu 18.04.3 LTS.
Yes i deleted the bower_components and node_modules directory and reinstalled both.
The same error :-(

**Comment by devprojectsapps** [comment]
What can i do?

**Comment by rejas** [comment]
I dont know. The file lib is something that should be there. Maybe something went wrong in your npm isntall?

**Comment by rejas** [comment]
Have you run "npm install" in your bower_components/modernizr  directory too?

**Comment by damian-cell** [comment]
https://github.com/Modernizr/Modernizr/issues/2509#issue-577553045
