### ISSUE TITLE
On M1 Mac (arm64) npm install fails.

### ISSUE THREAD

**Issue by yogarasu** [Modernizr/Modernizr#2696]
**Describe the bug**

On M1 Mac npm install fails.
Perhaps this is not only m1 mac, but I think that it is a problem that occurs with arm64 terminal.

**How to Reproduce**

I use volta for node version control.
https://docs.volta.sh/guide/

```zsh
volta install node@16.17.0 npm@8.15.0

npm i
```

```text
npm ERR! code 1
npm ERR! path /Users/xxx/modernizr/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh /var/folders/jn/06v19hd14n55vcd1203klmw80000gn/T/install-00ea8f05.sh
npm ERR! The chromium binary is not available for arm64: 
npm ERR! If you are on Ubuntu, you can install with: 
npm ERR! 
npm ERR!  apt-get install chromium-browser
npm ERR! 
npm ERR! /Users/xxx/modernizr/node_modules/puppeteer/lib/BrowserFetcher.js:112
npm ERR!             throw new Error();
npm ERR!             ^
npm ERR! 
npm ERR! Error
npm ERR!     at /Users/xxx/modernizr/node_modules/puppeteer/lib/BrowserFetcher.js:112:19
npm ERR!     at FSReqCallback.oncomplete (node:fs:206:21)

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2022-09-06T10_07_59_922Z-debug-0.log modernizr %npm i mocha-headless-chrome
npm ERR! code 1
npm ERR! path /Users/xxx/modernizr/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh /var/folders/jn/06v19hd14n55vcd1203klmw80000gn/T/install-4dc1219d.sh
npm ERR! The chromium binary is not available for arm64: 
npm ERR! If you are on Ubuntu, you can install with: 
npm ERR! 
npm ERR!  apt-get install chromium-browser
npm ERR! 
npm ERR! /Users/xxx/modernizr/node_modules/puppeteer/lib/BrowserFetcher.js:112
npm ERR!             throw new Error();
npm ERR!             ^
npm ERR! 
npm ERR! Error
npm ERR!     at /Users/xxx/modernizr/node_modules/puppeteer/lib/BrowserFetcher.js:112:19
npm ERR!     at FSReqCallback.oncomplete (node:fs:206:21)
...
```

**Expected behavior**

**Additional context**

I roughly understand the cause of this problem.
This is because the version of the `mocha-headless-chrome` package is old and the internally dependent `puppeteer` is old, so it is not compatible with arm64 chrome.

I solved it by upgrading the `mocha-headless-chrome` package to the latest 4.0.0 just in case.
Please consider upgrading this package.

**Comment by rejas** [comment]
Can this be closed now?

**Comment by yogarasu** [comment]
@rejas 
OK!
Thanks
